### ISSUE TITLE
deploy.ps1 Script is missing

### ISSUE THREAD

**Issue by AlexanderPBrown** [filipelteixeira/msft-mbf-composer-pokebot-pipeline#1]
The deployment directions mention a deploy.ps1 script file, but I can find no such file.  Please advise.

**Comment by filipelteixeira** [comment]
Hi Alexandre, deploy script is included in the automatic project generation on Bot Composer.

However, the goal of this repo is to exemplify the deployment through integrated pipelines, therefor the project is trimmed for that purpose.

Please refer to https://filipelteixeira.com/blog/how-to-devops-pipeline-for-bot-composer  for the article.

Also bear in mind that this files apply for Bot Composer V1, not the latest Microsoft version.
